dist: xenial
os: linux
language: python

# Set the python versions
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - python -m pip install pip==21.3.1
install:
  - pip install tox-travis
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then pip install codecov; fi

# command to run tests
script: tox

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.9" ]; then codecov; fi
