FROM quay.io/fedora/python-310:latest

USER root

RUN dnf install -y git

RUN git clone https://github.com/quadsproject/badfish

WORKDIR badfish

RUN git checkout development

RUN dnf install -y gcc python3-devel
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python -m build
RUN python -m pip install dist/badfish-*.tar.gz

ENTRYPOINT ["badfish"]
CMD ["-v"]
