---
name: RPM build
on:
  # Build only on pushes into master branch.
  push:
    branches: [ master ]

jobs:
  build:
    name: Submit a build from Fedora container
    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools copr-cli make zlib-devel

      - name: Work around GHA permission issue
        run: git config --global --add safe.directory /__w/badfish/badfish

      - name: Build the source RPM
        run: |
          cd rpm && make srpm

      - name: Submit the build by uploading the source RPM
        run: |
          copr build quadsdev/python3-badfish rpm/*.src.rpm
